import packageInfo from '../package.json';
import {useEffect,useRef,useState} from 'react';import {ArrowCounterClockwise,ArrowsOut,ArrowsIn,Pause,Play,SpeakerHigh,SpeakerSlash,SlidersHorizontal,BookOpen,X,ArrowRight} from '@phosphor-icons/react';
import {Matchmaker} from './matchmaker/Matchmaker.tsx';import type {MatchmakerHandle,Telemetry} from './matchmaker/Matchmaker.tsx';import {defaultOptions,normalizeOptions,stageNames} from './matchmaker/options.ts';import {OptionsPanel} from './OptionsPanel.tsx';
const storageKey='hearthstone-match-lab.v1';
function initialOptions(){try{const raw=localStorage.getItem(storageKey);return raw?normalizeOptions(JSON.parse(raw)):normalizeOptions(defaultOptions);}catch{return normalizeOptions(defaultOptions);}}
const empty:Telemetry={time:0,offset:3,velocity:0,stage:'idle',progress:0,fps:60,duration:9.55,paused:false,winner:'',particles:0,audio:'未激活'};
const motionFingerprint=(o:ReturnType<typeof initialOptions>)=>JSON.stringify([o.opponents,o.result,o.seed,o.acceleration,o.cruise,o.deceleration,o.settle,o.speed,o.direction,o.rebound,o.bounces]);
export function App(){
 const [options,setOptions]=useState(initialOptions),[telemetry,setTelemetry]=useState(empty),[showPanel,setShowPanel]=useState(true),[toast,setToast]=useState(''),[showAbout,setShowAbout]=useState(false),[fullscreen,setFullscreen]=useState(false);
 const matcher=useRef<MatchmakerHandle|null>(null);const aboutOpener=useRef<HTMLButtonElement|null>(null);const checkpoint=useRef(motionFingerprint(options));const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const embed=new URLSearchParams(location.search).get('embed')==='1';
 const active=['accelerating','spinning','decelerating','settling'].includes(telemetry.stage);const changed=motionFingerprint(options)!==checkpoint.current;
 const notify=(s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000);};
 useEffect(()=>{const id=setTimeout(()=>{try{localStorage.setItem(storageKey,JSON.stringify(options));}catch{notify('浏览器无法保存设置，仍可导出配置');}},350);return()=>clearTimeout(id);},[options]);
 useEffect(()=>{const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return()=>{document.removeEventListener('fullscreenchange',changed);if(toastTimer.current)clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{if(!showAbout)return;const previous=aboutOpener.current;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setShowAbout(false);if(e.key==='Tab'){const items=[...document.querySelectorAll<HTMLElement>('.about-modal button,.about-modal a')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[showAbout]);
 const start=async()=>{checkpoint.current=motionFingerprint(options);await matcher.current?.start();};
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('当前浏览器不支持全屏');}}
 const onTelemetry=(t:Telemetry)=>{if(t.stage==='accelerating'&&telemetry.stage!==t.stage)checkpoint.current=motionFingerprint(options);setTelemetry(t);};
 return <div className={`app ${!showPanel?'panel-hidden':''} ${embed?'embed-mode':''}`}>
  {!embed&&<header className="app-header"><div className="brand"><div className="brand-seal">H</div><div><h1>炉石匹配实验室</h1><span>HEARTHSTONE · MATCH LAB</span></div><span className="version-tag">CLASSIC</span></div><div className="header-actions"><button ref={aboutOpener} className="text-button" onClick={()=>setShowAbout(true)}><BookOpen size={17}/>复刻说明</button><span className="header-divider"/><button className="icon-button" aria-label={options.muted?'开启声音':'静音'} title={options.muted?'开启声音':'静音'} onClick={()=>setOptions(p=>({...p,muted:!p.muted}))}>{options.muted?<SpeakerSlash size={20}/>:<SpeakerHigh size={20}/>}</button><button className="icon-button" aria-label={fullscreen?'退出全屏':'全屏'} title="全屏" onClick={()=>void toggleFullscreen()}>{fullscreen?<ArrowsIn size={19}/>:<ArrowsOut size={19}/>}</button><button className={`panel-toggle ${showPanel?'selected':''}`} aria-label={showPanel?'隐藏参数':'显示参数'} onClick={()=>setShowPanel(v=>!v)}><SlidersHorizontal size={17}/><span>参数</span></button></div></header>}
  <main className="workspace"><section className="preview" aria-label="匹配界面预览"><div className="stage-backdrop" style={{opacity:options.brightness}}/><div className="stage-vignette"/>
   {!embed&&<div className="preview-heading"><span className="preview-kicker">经典匹配界面</span><div className="stage-badge"><span className={active?'status-dot running':'status-dot'}/>{telemetry.paused?'已暂停':stageNames[telemetry.stage]}</div></div>}
   <div className="match-stage"><div className="match-size" style={{transform:`scale(${options.scale})`}}><Matchmaker ref={matcher} options={options} onTelemetry={onTelemetry} onComplete={winner=>notify(`匹配成功 · ${winner.name}`)}/></div></div>
   {!embed&&<><div className="preview-caption"><span>{telemetry.stage==='complete'?telemetry.winner:'让每一次匹配，都恰到好处。'}</span><span className="render-label">实时渲染 / 高清材质</span></div><div className="playback-bar"><div className="playback-buttons"><button className="play-primary" aria-label={active?'重新匹配':'开始匹配'} onClick={()=>void start()}>{active?<ArrowCounterClockwise size={17}/>:<Play size={17} weight="fill"/>}<span>{active?'重播':'开始匹配'}</span></button><button className="icon-button" aria-label={telemetry.paused?'继续动画':'暂停动画'} disabled={!active} title={telemetry.paused?'继续':'暂停'} onClick={()=>telemetry.paused?void matcher.current?.resume():matcher.current?.pause()}>{telemetry.paused?<Play size={18} weight="fill"/>:<Pause size={18} weight="fill"/>}</button></div><div className="timeline"><input type="range" min={0} max={Number(telemetry.duration.toFixed(4))} step="any" value={telemetry.time} disabled={['idle','cancelled'].includes(telemetry.stage)} aria-label="动画时间轴" onChange={e=>matcher.current?.seek(Number(e.target.value))}/><div className="timeline-labels"><span>{telemetry.time.toFixed(2)} s</span><span>{telemetry.duration.toFixed(2)} s</span></div></div><div className="speed-badge">{options.playback.toFixed(2)}×</div></div></>}
  </section>{showPanel&&!embed&&<OptionsPanel options={options} setOptions={setOptions} matcher={matcher} telemetry={telemetry} onMessage={notify} changed={changed}/>}</main>
  {!embed&&<footer className="app-footer"><span><span className="footer-dot"/>React + TypeScript<span className="footer-separator">/</span>交互复刻实验 · v{packageInfo.version} <a href="https://github.com/holynova/hearthstone-match" target="_blank" rel="noreferrer">GitHub</a></span><div><span><b>{telemetry.fps}</b> FPS</span><span>粒子 <b>{telemetry.particles}</b></span><span>速度 <b>{Math.abs(telemetry.velocity).toFixed(1)}</b> 行/s</span><span className="resolution-label">{window.devicePixelRatio}× DPR</span></div></footer>}
  {toast&&!embed&&<div className="toast" role="status">{toast}</div>}
  {showAbout&&<div className="modal-backdrop" onClick={()=>setShowAbout(false)}><section className="about-modal" role="dialog" aria-modal="true" aria-label="复刻说明" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-button modal-close" aria-label="关闭说明" onClick={()=>setShowAbout(false)}><X size={20}/></button><span className="eyebrow">ABOUT THIS EXPERIMENT</span><h2>熟悉的等待，重新构建。</h2><p>参考经典炉石传说的机械滚筒匹配界面，重建材质、曲面文字、减速回弹与两侧火花。匹配器为独立 React 组件，参数面板用于手动实验。</p><p>这是界面模拟器，匹配结果由本地配置决定。默认音效和背景旋律由 Web Audio 合成；高清框体为根据参考重新生成的材质，未提取游戏原始模型。背景使用暴雪公开截图。</p><div className="about-links"><a href="https://hearthstone.blizzard.com/ru-ru/news/15019545" target="_blank" rel="noreferrer">暴雪官方界面参考<ArrowRight size={15}/></a><a href="https://www.youtube.com/watch?v=deTunPCWtD0" target="_blank" rel="noreferrer">经典匹配动画参考<ArrowRight size={15}/></a></div><button className="outline-button" onClick={()=>setShowAbout(false)}>返回实验</button></section></div>}
 </div>;
}
