import {useEffect,useState} from 'react';import type {Dispatch,SetStateAction,RefObject} from 'react';
import {ArrowCounterClockwise,ArrowSquareOut,DownloadSimple,UploadSimple,Waveform,SlidersHorizontal,PaintBrush,TextT,SpeakerHigh,Check} from '@phosphor-icons/react';
import {defaultOptions,numericRanges,normalizeOptions} from './matchmaker/options.ts';import type {MatchOptions} from './matchmaker/options.ts';import type {MatchmakerHandle,Telemetry} from './matchmaker/Matchmaker.tsx';import type {SoundKind} from './matchmaker/audio.ts';
type Tab='motion'|'visual'|'content'|'sound';
interface Props {options:MatchOptions;setOptions:Dispatch<SetStateAction<MatchOptions>>;matcher:RefObject<MatchmakerHandle|null>;telemetry:Telemetry;onMessage:(s:string)=>void;changed:boolean;}
function Slider({label,value,min,max,step=.1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void}){
 return <div className="parameter"><div className="parameter-title"><label htmlFor={`slider-${label}`}>{label}</label><div className="numeric"><input aria-label={`${label}数值`} type="number" value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))onChange(Math.min(max,Math.max(min,e.target.valueAsNumber)));}}/><span>{unit}</span></div></div><input id={`slider-${label}`} type="range" aria-label={label} min={min} max={max} step="any" value={value} onChange={e=>onChange(Number(e.target.value))}/></div>;
}
export function OptionsPanel({options:o,setOptions,matcher,telemetry:t,onMessage,changed}:Props){
 const [tab,setTab]=useState<Tab>('motion');const [draft,setDraft]=useState('');const [error,setError]=useState('');const [files,setFiles]=useState<Partial<Record<SoundKind,string>>>({});
 useEffect(()=>{setDraft(o.opponents.map(i=>`${i.name} | ${i.weight}`).join('\n'));setError('');},[o.opponents]);
 const update=(key:keyof MatchOptions,value:unknown)=>setOptions(prev=>({...prev,[key]:value}));
 const slider=(key:keyof MatchOptions,label:string,unit='',step=.1)=>{const r=numericRanges[key]!;return <Slider key={key} label={label} value={o[key] as number} min={r[0]} max={r[1]} step={step} unit={unit} onChange={v=>update(key,v)}/>;};
 function preset(value:string){if(value==='classic')setOptions(normalizeOptions(defaultOptions));if(value==='slow')setOptions(normalizeOptions({...defaultOptions,playback:.25,cruise:3,blur:3,particles:30}));if(value==='cinematic')setOptions(normalizeOptions({...defaultOptions,speed:26,cruise:7,deceleration:4,rebound:.8,bounces:3,particles:110,glow:1.1}));onMessage('预设已应用，点击重播查看');}
 function exportConfig(){const blob=new Blob([JSON.stringify({version:1,options:o},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hearthstone-match-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);onMessage('配置已导出');}
 async function importConfig(file:File){try{if(file.size>500000)throw new Error('配置文件过大');const json=JSON.parse(await file.text());setOptions(normalizeOptions(json.options??json));onMessage('配置已导入');}catch(e){onMessage(`导入失败：${(e as Error).message}`);}}
 function applyCandidates(){try{const names=draft.split('\n').filter(i=>i.trim()).map(line=>{const [name,weight]=line.split('|');return {name:name.trim(),weight:weight===undefined?1:Number(weight.trim())};});setOptions(normalizeOptions({...o,opponents:names}));setError('');onMessage('候选名单已更新');}catch(e){setError((e as Error).message);}}
 return <aside className="options-panel" aria-label="实验参数面板"><div className="panel-heading"><div><span className="eyebrow">CONTROL ROOM</span><h2>实验参数</h2></div><span className={`live-indicator ${changed?'pending':''}`}>{changed?'待重播':'实时'}</span></div>
  <div className="preset-row"><label htmlFor="preset">预设</label><select id="preset" defaultValue="" onChange={e=>{preset(e.target.value);e.currentTarget.value='';}}><option value="" disabled>选择实验预设</option><option value="classic">经典复刻</option><option value="slow">慢动作观察</option><option value="cinematic">强化动效</option></select></div>
  <div className="panel-tabs" role="tablist" aria-label="参数分类">{([{id:'motion',label:'动画',Icon:SlidersHorizontal},{id:'visual',label:'画面',Icon:PaintBrush},{id:'content',label:'内容',Icon:TextT},{id:'sound',label:'声音',Icon:SpeakerHigh}] as const).map(({id,label,Icon})=><button key={id} role="tab" id={`tab-${id}`} aria-controls={`pane-${id}`} aria-selected={tab===id} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</div>
  <div className="panel-scroll" role="tabpanel" id={`pane-${tab}`} aria-labelledby={`tab-${tab}`} tabIndex={0}>
   {tab==='motion'&&<><div className="group-heading">滚筒运动<span>下次匹配生效</span></div>{slider('speed','滚动速度','行/秒',1)}{slider('acceleration','加速时间','秒',.05)}{slider('cruise','匀速时间','秒',.1)}{slider('deceleration','减速时间','秒',.1)}<div className="segmented-label">滚动方向<div className="segment"><button className={o.direction===1?'selected':''} onClick={()=>update('direction',1)}>向上</button><button className={o.direction===-1?'selected':''} onClick={()=>update('direction',-1)}>向下</button></div></div><div className="group-heading">停靠回弹</div>{slider('rebound','回弹幅度','行',.05)}{slider('bounces','回弹次数','次',1)}{slider('settle','停稳时间','秒',.1)}<div className="group-heading">播放控制<span>即时生效</span></div>{slider('playback','播放倍率','×',.05)}<p className="panel-note">运动轨迹在开始时固定。修改速度或回弹后重播，可使用相同种子复现实验。</p></>}
   {tab==='visual'&&<><div className="group-heading">画面表现<span>即时生效</span></div>{slider('scale','界面缩放','×',.05)}{slider('fontSize','滚筒字号','px',1)}{slider('blur','运动模糊','',.5)}{slider('glow','辉光强度','',.05)}{slider('brightness','背景亮度','',.05)}{slider('pointerShake','指针抖动','°',.1)}<div className="group-heading">火花粒子</div>{slider('particles','发射数量','个/秒',1)}{slider('particleSpeed','初始速度','px/秒',5)}{slider('life','粒子寿命','秒',.05)}{slider('gravity','重力','px/秒²',5)}{slider('particleSize','粒子尺寸','px',.1)}<p className="panel-note">文字和粒子按屏幕像素密度绘制。背景、外壳与滚筒分层渲染。</p></>}
   {tab==='content'&&<><div className="group-heading">文字内容</div><label className="field">页面标题<input value={o.title} maxLength={20} onChange={e=>update('title',e.target.value)}/></label><label className="field">底部提示<textarea rows={3} maxLength={160} value={o.tip} onChange={e=>update('tip',e.target.value)}/></label><div className="group-heading">候选对手<span>{o.opponents.length} 项</span></div><label className="field">每行一个名称，可用 | 设置权重<textarea className="candidate-input" rows={9} value={draft} maxLength={6000} onChange={e=>setDraft(e.target.value)} spellCheck={false}/></label>{error&&<p className="field-error" role="alert">{error}</p>}<button className="outline-button full" onClick={applyCandidates}><Check size={15}/>应用名单</button><label className="field">匹配结果<select value={o.result} onChange={e=>update('result',e.target.value)}><option value="">按权重随机选择</option>{o.opponents.map(i=><option key={i.name}>{i.name}</option>)}</select></label>{slider('seed','随机种子','',1)}<p className="panel-note">经典预设固定停在“旗鼓相当的对手”。也可以选择任意结果，或按权重随机匹配。</p></>}
   {tab==='sound'&&<><div className="group-heading">音频混音<span>即时生效</span></div><label className="toggle-row">静音<input type="checkbox" checked={o.muted} onChange={e=>update('muted',e.target.checked)}/></label>{slider('volume','总音量','',.05)}{slider('mechanicalVolume','机械音效','',.05)}{slider('successVolume','成功提示','',.05)}{slider('musicVolume','背景旋律','',.05)}<div className="group-heading">替换音频<span>本次会话</span></div>{([{kind:'start',label:'启动声'},{kind:'tick',label:'卡齿声'},{kind:'success',label:'成功声'},{kind:'cancel',label:'取消声'},{kind:'music',label:'背景音乐'}] as const).map(({kind,label})=><div className="sound-file" key={kind}><button className="sound-preview" aria-label={`试听${label}`} onClick={()=>void matcher.current?.previewSound(kind)}><Waveform size={16}/></button><div><strong>{label}</strong><small>{files[kind]??'合成音效'}</small></div><label className="upload-button" title={`替换${label}`}><UploadSimple size={16}/><input type="file" aria-label={`替换${label}`} accept="audio/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>20*1024*1024)throw new Error('请选择小于 20 MB 的音频');await matcher.current?.loadSound(kind,f);setFiles(p=>({...p,[kind]:f.name}));onMessage(`${label}已替换`);}catch(err){onMessage(`音频加载失败：${(err as Error).message}`);}e.target.value='';}}/></label></div>)}<button className="text-button" onClick={()=>{matcher.current?.resetSounds();setFiles({});onMessage('已恢复合成音效');}}>恢复默认音频</button><p className="panel-note">默认声音由 Web Audio 合成，未使用游戏原版音轨。替换文件仅保留在本次会话，配置导出不包含音频。</p></>}
  </div>
  <div className="panel-bottom"><div className="telemetry-mini"><span>引擎状态</span><span>{t.audio==='running'?'音频已激活':'点击匹配启用声音'}</span></div><div className="config-actions"><button title="恢复默认参数" aria-label="恢复默认参数" onClick={()=>{setOptions(normalizeOptions(defaultOptions));onMessage('已恢复默认参数');}}><ArrowCounterClockwise size={17}/></button><button onClick={exportConfig}><DownloadSimple size={16}/>导出</button><label><UploadSimple size={16}/>导入<input aria-label="导入配置" type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void importConfig(f);e.target.value='';}}/></label></div></div>
 </aside>;
}
